export const ITEMS = [
  { slug: "water-meter-leak-test", art: "meter", kicker: "كشف التسربات", title: "فحص عداد الماي\nواكتشاف التهريب المخفي", en: "The water meter test\nfor hidden leaks", enK: "Leak detection",
    info: { file: "water-meter-leak-test-steps", title: "اختبار العداد بـ 4 خطوات", items: ["سكّر كل الحنفيات والأجهزة", "صوّر أرقام العداد", "انتظر 30 دقيقة بدون استخدام", "قارن: إذا تغيرت الأرقام في تهريب"] } },
  { slug: "ppr-vs-copper-pipes", art: "pipes", kicker: "تمديد المواسير", title: "PPR ولا نحاس؟\nدليل اختيار المواسير", en: "PPR or copper?\nChoosing your pipes", enK: "Pipework",
    info: { file: "ppr-vs-copper-pipes-compare", title: "مقارنة سريعة", items: ["PPR: ما يصدّي ووصلاته ملحومة", "النحاس: قوي ويتحمل الحرارة", "PVC: للصرف والمجاري بس", "اختبار الضغط قبل التبليط دايمًا"] } },
  { slug: "bathroom-rough-in-mistakes", art: "bath", kicker: "تأسيس الحمامات", title: "7 أخطاء بتأسيس الحمام\nتكلفك بعد التبليط", en: "7 bathroom rough-in\nmistakes to avoid", enK: "Bathrooms",
    info: { file: "bathroom-rough-in-mistakes-checklist", title: "قبل التبليط تأكد من", items: ["ميلان الصرف مقاس بالميزان", "فتحة تنظيف يوصلها الفني", "الحار والبارد مفصولين", "اختبار ضغط والمؤشر ثابت", "محبس خاص للحمام"] } },
  { slug: "toilet-cistern-running", art: "toilet", kicker: "تسريب السيفون", title: "السيفون يصفّر\nوما يوقف ماي؟", en: "Running toilet\ncistern?", enK: "Leaks",
    info: { file: "toilet-cistern-running-test", title: "اختبار صبغ الطعام", items: ["افتح غطا خزان السيفون", "حط كم نقطة صبغ ملون", "لا تسحب وانتظر ربع ساعة", "وصل اللون للكرسي؟ في تهريب"] } },
  { slug: "manhole-overflow", art: "manhole", kicker: "تسليك المجاري", title: "المنهول فايض؟\nشنو تسوي وليش يصير", en: "Overflowing\nmanhole?", enK: "Drains",
    info: { file: "manhole-overflow-steps", title: "شلون ينحل الانسداد", items: ["شفط المنهول من الماي والرواسب", "كاميرا داخل الخط تحدد السدّة", "تسليك بماكينة ضغط عالي", "تنظيف الغرفة وإرجاع الغطا"] } },
  { slug: "water-heater-types-guide", art: "heater", kicker: "السخانات", title: "سخان فوري\nولا سخان خزان؟", en: "Instant or tank\nwater heater?", enK: "Water heaters",
    info: { file: "water-heater-types-guide-compare", title: "الفرق باختصار", items: ["الخزان: كمية كبيرة بنفس الوقت", "الفوري: ماي حار ما يخلص", "المركزي: للفلل والحمامات الوايد", "صمام أمان وتأريض لكل سخان"] } },
  { slug: "choose-water-pump", art: "pump", kicker: "المضخات", title: "شلون تختار\nماطور الماي المناسب", en: "Choosing the right\nwater pump", enK: "Water pumps",
    info: { file: "choose-water-pump-factors", title: "اللي يحدد حجم الماطور", items: ["عدد أدوار البيت", "النقاط اللي تشتغل بنفس الوقت", "مكان التانكي: أرضي ولا علوي", "مكان مظلل وحماية من التشغيل على الناشف"] } },
  { slug: "dripping-tap-mixer", art: "tap", kicker: "الحنفيات والخلاطات", title: "الحنفية تنقّط؟\nالأسباب والحل", en: "Dripping tap\nor mixer?", enK: "Taps & mixers",
    info: { file: "dripping-tap-mixer-parts", title: "أشهر أسباب التنقيط", items: ["جلدة أو حلقة مطاطية تعبت", "قلب الخلاط خربان", "أملاح وترسبات داخلية", "ضغط ماي زايد"] } },
  { slug: "kuwait-summer-plumbing", art: "sun", kicker: "السباكة بالصيف", title: "صيف الكويت\nوالماي البارد اللي يطلع حار", en: "Kuwait summer\nand your plumbing", enK: "Seasonal tips",
    info: { file: "kuwait-summer-plumbing-tips", title: "احمِ شبكتك بالصيف", items: ["ظلّل أو اعزل التانكي", "اعزل المواسير المكشوفة", "الماطور بمكان مظلل", "طفّ السخان بعز الصيف"] } },
];
